version: "2"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /data/postgres
    restart: always
    env_file:
      - .env.development
  booster:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ".:/www"
    restart: on-failure
    depends_on:
      - postgres
